document.write(' \
<ul> \
  <li>A.A. Shahid, A. Moroncelli, D. Brščić, T. Kanda, L. Roveda, <span class="italic">GEAR: Gaze-Enabled Human-Robot Collaborative Assembly </span>, 2025 IEEE/RSJ International Conference on Intelligent Robots and Systems (IROS), October 2025</li> \
  <li>R. Ramnauth, D. Brščić, B. Scassellati, <span class="italic">From Fidgeting to Focused: Developing Robot-Enhanced Social-Emotional Therapy (RESET) for School De-Escalation Rooms</span>, 34th IEEE International Conference on Robot and Human Interactive Communication (RO-MAN), August 2025</li> \
  <li>D. Brščić, B. Scassellati, <span class="italic">Nudging Without Words: Movement-Only Influence by a Robot Manipulator</span>, 34th IEEE International Conference on Robot and Human Interactive Communication (RO-MAN), August 2025</li> \
  <li>N. Georgiou, S. Wang, J. Banks, K. Candon, D. Brščić, B. Scassellati, <span class="italic">When Teaching A Robot, People Employ Different Feedback Strategies: Some Are More Effective Than Others</span>, 47th Annual Meeting of the Cognitive Science Society (CogSci), July/August 2025</li> \
  <li>R. Ramnauth, D. Brščić, B. Scassellati, <span class="italic">A Robot-Assisted Approach to Small Talk Training for Adults with ASD</span>, Robotics: Science and Systems (RSS), June 2025</li> \
  <li>H. Nakashima, D. Brščić, T. Kanda, <span class="italic">Exploring the Use of Smell in Social Interaction via Robot Avatars</span>, 2025 ACM/IEEE International Conference on Human-Robot Interaction (HRI), pp. 113-122, March 2025</li> \
  <li>K. Du, D. Brščić, T. Kanda, <span class="italic">Don\'t Just Stop Here! Human-Inspired Solutions for Sudden Robot Stops</span>, 2025 ACM/IEEE International Conference on Human-Robot Interaction (HRI), pp. 293-302, March 2025</li> \
  <li>R. Ramnauth, D. Brščić, B. Scassellati, <span class="italic">Should I Help?: A Skill-Based Framework for Deciding Socially Appropriate Assistance in Human-Robot Interactions</span>, 2024 33rd IEEE International Conference on Robot and Human Interactive Communication (ROMAN), pp. 2051-2058, Pasadena, CA, USA, August 2024</li> \
  <li>Z. Abbas, D. Brščić, T. Kanda, <span class="italic">Identifying and Detecting Inadvertent Socially Inappropriate Movement of Avatar Robots</span>, 2024 33rd IEEE International Conference on Robot and Human Interactive Communication (ROMAN), pp. 1864-1871, Pasadena, CA, USA, August 2024</li> \
  <li>S. Edirisinghe, S. Satake, D. Brščić, Y. Liu, T. Kanda, <span class="italic">Field Trial of an Autonomous Shopworker Robot that Aims to Provide Friendly Encouragement and Exert Social Pressure</span>, 2024 ACM/IEEE International Conference on Human-Robot Interaction (HRI), pp. 194-202, March 2024</li> \
  <li>K. Du, D. Brščić, Y. Liu, T. Kanda, <span class="italic">Can’t You See I Am Bothered? Human-inspired Suggestive Avoidance for Robots</span>, 2024 ACM/IEEE International Conference on Human-Robot Interaction (HRI), pp. 184-193, March 2024</li> \
  <li>H. Nakashima, D. Brščić, T. Kanda, <span class="italic">Expanding the Senses: Considering the Use of Active Smell Delivery for Human-Robot Interactions</span>, 11th International Conference on Human-Agent Interaction (poster), pp. 479-481, December 2023</li> \
  <li>K. Winkle, R.B. Jackson, G.I. Melsion, D. Brščić, I. Leite, T. Williams, <span class="italic">Norm-Breaking Responses to Sexist Abuse: A Cross-Cultural Human Robot Interaction Study</span>, 2022 ACM/IEEE International Conference on Human-Robot Interaction (HRI), pp. 120-129, March 2022</li> \
  <li>C. Feliciani, S. Tanida, M. Furukawa, H. Murakami, X. Jia, D. Brščić, K. Nishinari, <span class="italic">“Nudging” Crowds: When It Works, When It Doesn’t and Why</span>, 2022 International Conference on Traffic and Granular Flow, in Lecture Notes in Civil Engineering, vol 443, pp. 11-18, Springer, Singapore, 2022</li> \
  <li>R. Maeda, D. Brščić, and T. Kanda, <span class="italic">Influencing Moral Behavior Through Mere Observation of Robot Work: Video-based Survey on Littering Behavior</span>, 2021 ACM/IEEE International Conference on Human-Robot Interaction (HRI), pp. 83–91, March 2021</li> \
  <li>K. Makita, D. Brščić, and T. Kanda, <span class="italic">Recognition of Human Characteristics Using Multiple Mobile Robots with 3D LiDARs</span>, 2021 IEEE/SICE International Symposium on System Integration (SII), pp. 650-655, Iwaki, Japan, January 2021</li> \
  <li>A. Nanavati, M. Doering, D. Brščić, and T. Kanda, <span class="italic">Autonomously Learning One-To-Many Social Interaction Logic from Human-Human Interaction Data</span>, 2020 ACM/IEEE International Conference on Human-Robot Interaction (HRI), Cambridge, UK, March 2020</li> \
  <li>D. Ilić, I. Žužić, D. Brščić, <span class="italic">Calibrate My Smile: Robot Learning Its Facial Expressions through Interactive Play with Humans</span>, 7th International Conference on Human-Agent Interaction (HAI), pp. 68–75, Kyoto, Japan, October 2019</li> \
  <li>S. Satake, T. Kaczmarek, D. Brščić and T. Kanda, <span class="italic">Facilitating Software Development for Mobile Social Robots by Simulating Interactions Between a Robot and Pedestrians</span>, 14th ACM/IEEE International Conference on Human-Robot Interaction (HRI), pp. 626-627, Daegu, Korea (South), 2019</li> \
  <li>D. Brščić, F. Zanlungo, T. Kanda, <span class="italic">Modelling of Pedestrian Groups and Application to Group Recognition</span>, 40th International Convention on Information and Communication Technology, Electronics and Microelectronics (MIPRO), Opatija, Croatia, May 2017</li> \
  <li>D.F. Glas, D. Brščić, T. Miyashita, N. Hagita, <span class="italic">SNAPCAT-3D: Calibrating Networks of 3D Range Sensors for Pedestrian Tracking</span>, IEEE International Conference on Robotics and Automation ICRA 2015, pp. 712-719, Seatle, USA, May 2015</li> \
  <li>D. Brščić, H. Kidokoro, Y. Suehiro, T. Kanda, <span class="italic">Escaping from Children’s Abuse of Social Robots</span>, 10th ACM/IEEE International Conference on Human-Robot Interaction HRI 2015, pp. 59-66, Portland, USA, March 2015<span class="award"><i class="fas fa-trophy blink"></i>Best Paper Award "Best Enabling Field Studies"<i class="fas fa-trophy blink"></i></span></li> \
  <li>D. Brščić, F. Zanlungo, T. Kanda, <span class="italic">Density and Velocity Patterns during One Year of Pedestrian Tracking</span>, Conference on Pedestrian and Evacuation Dynamics PED 2014, October 2014 (in Transportation Research Procedia, Vol. 2, pp. 77-86, 2014)</li> \
  <li>F. Zanlungo, D. Brščić, T. Kanda, <span class="italic">Pedestrian Group Behaviour Analysis under Different Density Conditions</span>, Conference on Pedestrian and Evacuation Dynamics PED 2014, October 2014 (in Transportation Research Procedia, Vol. 2, pp. 149-158, 2014)</li> \
  <li>D. Brščić, <span class="italic">Social robots in smart public environments</span>, 2014 IEEE 3rd Global Conference on Consumer Electronics (GCCE), pp. 651-653, October 2014 (<span class="italic">invited presentation</span>) </li> \
  <li>H. Kidokoro, T. Kanda, D. Brščić, M. Shiomi, <span class="italic">Will I bother here? - A robot anticipating its influence on pedestrian walking comfort</span>, 8th ACM/IEEE International Conference on Human-Robot Interaction HRI 2013, pp. 259-266, Tokyo, Japan, March 2013<span class="award"><i class="fas fa-trophy blink"></i>Best Paper Award<i class="fas fa-trophy blink"></i></span></li> \
  <li>X. Zang, D. Brščić, W. Wang, K. Kuehnlenz, <span class="italic">Temporal Attention Control System for Multiple Objects Tracking</span>, The 31st Chinese Control Conference (CCC 2012), pp. 4836-4841, Hefei, China, July 2012</li> \
  <li>W. Wang, D. Brščić, Z. He, S. Hirche, K. Kuehnlenz, <span class="italic">Real-time human body motion estimation based on multi-layer laser scans</span>, IEEE International Conference on Ubiquitous Robots and Ambient Intelligence URAI 2011, pp. 297-302, Incheon, Korea, November 2011</li> \
  <li>F. Rohrmueller, O. Kourakos, M. Rambow, D. Brščić, D. Wollherr, S. Hirche, M. Buss, <span class="italic">Interconnected Performance Optimization in Complex Robotic Systems</span>, IEEE/RSJ International Conference on Intelligent Robots and Systems IROS 2010, pp. 4113-4118, Taipei, Taiwan, October 2010</li> \
  <li>D. Brščić, H. Hashimoto, <span class="italic">Model based robot localization using onboard and distributed laser range finders</span>, in Proceedings of the IEEE/RSJ International Conference on Intelligent Robots and Systems IROS 2008, pp. 1154-1159, Nice, France, November 2008</li> \
  <li>D. Brščić, H. Hashimoto, <span class="italic">Comparison of robot localization methods using distributed and onboard laser range finders</span>, in Proceedings of the IEEE/ASME International Conference on Advanced Intelligent Mechatronics AIM 2008, pp. 746-751, Xi’an, China, July 2008</li> \
  <li>P. Zanaty, D. Brščić, Z. Frei, <span class="italic">3D Visualization for Intelligent Space: Time-Delay Compensation in a Remote Controlled Environment</span>, in Proceedings of the Conference on Human System Interactions HSI 2008, pp. 802-807, Krakow, Poland, May 2008</li> \
  <li>D. Brščić, H. Hashimoto, <span class="italic">Tracking of Humans Inside Intelligent Space using Static and Mobile Sensors</span>, IEEE International Conference on Industrial Electronics IECON 2007, pp. 10-15, Taipei, Taiwan, November 2007</li> \
  <li>D. Brščić, H. Hashimoto, <span class="italic">Map building and object tracking inside Intelligent Spaces using static and mobile sensors</span>, IEEE International Conference on Robotic Systems IROS 2007, pp. 3751-3756, San Diego, USA, October 2007 <span class="award"><i class="fas fa-trophy blink"></i>IEEE RAS Japan Chapter Young Award<i class="fas fa-trophy blink"></i></span></li> \
  <li>D. Brščić, T. Sasaki, H. Hashimoto, <span class="italic">Acting in Intelligent Space -Mobile robot control based on sensors distributed in space-</span>, IEEE/ASME International Conference on Advanced Intelligent Mechatronics AIM 2007, paper 148 (6 pages), Zuerich, Switzerland, September 2007 </li> \
  <li>T. Sasaki, D. Brščić, H. Hashimoto, <span class="italic">Implementation of Distributed Sensor Network for Intelligent Space</span>, IEEE International Conference on Mechatronics (ICM 2007), TuA1-B-1, Kumamoto Japan, May 2007</li> \
  <li>D. Brščić, H. Hashimoto, <span class="italic">Tracking of Objects in Intelligent Space Using Laser Range Finders</span>, IEEE International Conference on Industrial Technology ICIT 2006, Mumbai India, pp. 1723-1728, December 2006</li> \
  <li>D. Brščić, T. Sasaki, H. Hashimoto, <span class="italic">Implementation of Mobile Robot Control in Intelligent Space</span>, SICE-ICCAS International Joint Conference 2006, pp. 1228-1233, Busan Korea, October 2006</li> \
  <li>T. Sasaki, K. Morioka, P.T. Szemes, D. Brščić, H. Hashimoto, <span class="italic">Moving Object Tracking and an Application in Intelligent Space</span>, SICE Annual Conference 2005, pp.2326-2329, Okayama Japan, 2005</li> \
  <li>D. Brščić, <span class="italic">Tool for Remote Control of Mobile Robots with Visualization by Means of Virtual Reality</span>, 7th International Conference on Telecommunications - ConTEL 2003, Vol. 2, pp. 673-675, Zagreb Croatia, 2003</li> \
  <li>D. Brščić, I. Petrovic, N. Peric, <span class="italic">ATM Available Bit Rate Congestion Control with On-line Network Model Identification</span>, 9th IEEE International Conference on Electronics, Circuits and Systems - ICECS 2002 September 15-18, pp. 1243-1246., Dubrovnik Croatia, 2002</li> \
</ul> \
');
